### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Nbgreen** [Trixtaro/TrixtaLogin#1]
hi this isn't really an issue its more of a request. I was wondering if you could make it an option of where only people with a set perm have to login with the password. I just want to use this to lock my admins accounts so if some how someone was to log in as them they couldn't use the admins perms.

**Comment by Taurenboy** [comment]
Hi, I'm trying to use this but when I try to login I get this error:

Taurenboy joined the game
[21:01:41] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: Taurenboy lost connection: You need to login/register under the limit time.
[21:01:41] [Server thread/INFO] [minecraft/DedicatedServer]: Taurenboy left the game
[21:01:41] [Server thread/WARN] [minecraft/NetworkManager]: handleDisconnection() called twice

And my game crashed. I cant enter to the server so I cant register. Also I would like to work with you in this project.

¿Hablas español? o.o

**Comment by Trixtaro** [comment]
Hola, como estas, si hablo español, agregaste el tiempo para poder reigstrarte o logearte??

**Comment by Trixtaro** [comment]
Agregue un archivo de configuración como ejemplo para que veas como debe ser la configuración.
El archivo debe ponerse en la carpeta "config"

**Comment by Taurenboy** [comment]
Hola, agregué la configuración y ahora funciona, muchas gracias.
en archivo que has puesto de ejemplo tiene extención cnf y no me ha funcionado, he utilizado el archivo .conf que se genera automaticamente.
Veo que mientras tiene tiempo el usuario para logear se puede mover, supongo que son cosas que irás implementando.
Un saludo.

**Comment by Trixtaro** [comment]
Hola, si, fue un error mio, ya le cambie la extensión. Si quieres te agrego como colaborador para poder trabajar en el plugin. Un saludo.

**Comment by Drezzlo** [comment]
Hola, he descargado el pluguin pero no me da tiempo para registrarme. segun en la carpeta de configuración, aparece trixtalogin.conf pero coloque el comando: Configuration{ “wait_time”=15 }
pero me sigue dando error. no sé como configurarlo para aumentarle el tiempo de registro

**Comment by Trixtaro** [comment]
@Drezzlo en el repositorio existe un ejemplo de archivo de configuracion, pruebalo y me dices si tienes algun otro inconveniente

**Comment by lfre4000l** [comment]
Hola, tengo una duda como puedo configurar para que quien se este logeando no pueda escribir en el chat cosas o comandos aparte del /login /register, tambien que no se muevan , no abran inventario y no puedan interactuar con el mundo hasta logearse

**Comment by Trixtaro** [comment]
Esas caracteristicas todavia no se encuentran implementadas en el plugin. Puedes realizar el fork de este proyecto e implementarlas y realizar un PR para que se una a la version oficial.
