### ISSUE TITLE
Hola, tengo un problema !! me ayudan?

### ISSUE THREAD

**Issue by SebasCachetes** [Trixtaro/TrixtaLogin#10]
bueno, les explico, la cosa es que instale el plugin pero cuando intento entrar al servidor me saca automáticamente, y al mirar la consola veo que es porque se termino el tiempo de espera para el inicio de sesion, pero no se como cambiarlo

(aclaro  que estoy usando la versión de Forge)

**Comment by Trixtaro** [comment]
Hola, explico como resolverlo en el issue #7
