### ISSUE TITLE
Hola, tengo un problema

### ISSUE THREAD

**Issue by victorqh** [Trixtaro/TrixtaLogin#11]
Buscando un plugin para forge de Registro y login encontré TrixtaLogin. Pero tengo ciertas cosas que no sé como configurar. Me gustaría hacer que los players antes de logearse o registrarse no puedan:
- Moverse
- Ver inventario
- Escribir

Porque a pesar de tener un tiempo limite para estar conectado sin logearse pueden hacer mucho más y creo que ustedes ya lograron corregir ese desperfecto.

**Comment by Trixtaro** [comment]
Ya esta resuelto el problema de no poder moverse, pero todavía se puede escribir o ver el inventario. Descarga nueva última versión en **releases**
