### ISSUE TITLE
Tengo un problema y soy nuevo en esto, ¿me podrías ayudar?

### ISSUE THREAD

**Issue by Alfonso87639** [Trixtaro/TrixtaLogin#7]
He puesto el plugin y todo va bien, los jugadores se pueden registrar y logear, y si no lo hacen los kickea en 15 segundos, pero no puedo lograr que en el chat les diga a los usuarios que deben poner el comando /register o /login, y tampoco puedo lograr que no se muevan o chateen mientras lo hacen :(
Veo que en esta página dice Edit el jugador no se mueve hasta logearse y ahora solo se puede registrar 1 vez, pero no entiendo qué debo hacer con ello, ¿agrego todo eso al archivo trixtalogin.conf
o creo una carpeta y meto todo eso en archivos diferentes? ¿De ser así, como hago esos archivos .conf o .java? Gracias de antemano

**Comment by Trixtaro** [comment]
Hola, solo es un archivo de configuración, no debes guardarlo dentro de una carpeta. Debes colocar ese archivo de configuración dentro de la carpeta donde estan los archivos de configuración de los otros plugins.

**Comment by Trixtaro** [comment]
> He puesto el plugin y todo va bien, los jugadores se pueden registrar y logear, y si no lo hacen los kickea en 15 segundos, pero no puedo lograr que en el chat les diga a los usuarios que deben poner el comando /register o /login, y tampoco puedo lograr que no se muevan o chateen mientras lo hacen :(
> Veo que en esta página dice Edit el jugador no se mueve hasta logearse y ahora solo se puede registrar 1 vez, pero no entiendo qué debo hacer con ello, ¿agrego todo eso al archivo trixtalogin.conf
> o creo una carpeta y meto todo eso en archivos diferentes? ¿De ser así, como hago esos archivos .conf o .java? Gracias de antemano

Si esta programado que aparezca el mensaje, pero capaz te falta el archivo de configuración para que se muestre. Copia el archivo de ejemplo que esta en el repositorio **trixtarologin.conf**

**Comment by Alfonso87639** [comment]
Muchas gracias bro, me sirvió :D
