### ISSUE TITLE
config "wait_time" being ignored

### ISSUE THREAD

**Issue by k1r0s** [Trixtaro/TrixtaLogin#9]
Hola,

Im facing the same issue here: https://github.com/Trixtaro/TrixtaLogin/issues/7

I've updated the config to include wait_time but I don't see any changes so nobody is able to join my server and I ended up removing the plugin.

Spanish: he añadido la configuración q se comenta en el ticket mencionado anterior pero sigo viendo el mismo problema. Sin embargo el autor del ticket anterior comenta que si le sirvió. :\ que puede suceder?

**Comment by k1r0s** [comment]
error mio

**Comment by edgarlore** [comment]
Como lo iciste podrias ayudarme?

**Comment by Trixtaro** [comment]
Tienes que copiar el archivo de configuración **trixtalogin.conf** que esta en el repositorio y pegarlo en la configuración de tus plugins ya que no se genera automáticamente.
